apiVersion: v1
kind: Service
metadata:
  name: customer-churn-prediction-api-service
spec:
  selector:
    app: customer-churn-prediction-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
