name: Build and Push to Docker Hub

on:
  push:
    tags:
      - 'v*'   # Runs on version tags like v1.0.0, v2.3.1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if tag points to main branch
      id: check_branch
      run: |
        git fetch origin main --depth=1
        TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
        MAIN_COMMIT=$(git rev-parse origin/main)

        echo "Tag commit: $TAG_COMMIT"
        echo " Main commit: $MAIN_COMMIT"

        if [ "$TAG_COMMIT" = "$MAIN_COMMIT" ]; then
          echo "Tag points to main"
          echo "on_main=true" >> $GITHUB_OUTPUT
        else
          echo "Tag does NOT point to main"
          echo "on_main=false" >> $GITHUB_OUTPUT
        fi

    - name: Extract version from tag
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      if: steps.check_branch.outputs.on_main == 'true'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build Docker image
      if: steps.check_branch.outputs.on_main == 'true'
      run: docker build -t jagadish9084/customer-churn-prediction-api:${VERSION} .

    - name: Push Docker image
      if: steps.check_branch.outputs.on_main == 'true'
      run: docker push jagadish9084/customer-churn-prediction-api:${VERSION}

    - name: Zip the manifests
      if: steps.check_branch.outputs.on_main == 'true'
      run: |
        cd k8s
        zip -r ../k8s-manifests-${VERSION}.zip .

    - name: Upload artifact
      if: steps.check_branch.outputs.on_main == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: k8s-manifests-${{ env.VERSION }}
        path: k8s-manifests-${{ env.VERSION }}.zip
        retention-days: 30

    - name: Skip Info
      if: steps.check_branch.outputs.on_main == 'false'
      run: echo "This tag does not point to main — skipping Docker and artifact upload."
